In [ ]:
import numpy as np

1.**Data Creation:**Create suitable arrays to represent students, subjects, and their marks.

In [ ]:
students=np.array([1,2,3,4,5])
subjects=np.array([1,2,3,4])
marks=np.array([
    [65,75,86,98],
    [75,77,78,79],
    [89,57,68,90],
    [90,95,68,89],
    [80,85,88,90]])
print(students)
print(subjects)
print(marks)

[1 2 3 4 5]
[1 2 3 4]
[[65 75 86 98]
 [75 77 78 79]
 [89 57 68 90]
 [90 95 68 89]
 [80 85 88 90]]


2.**Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.

In [ ]:
print(marks.ndim)
print(marks.size)
print(marks.shape)

2
20
(5, 4)


3.Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.

In [ ]:
reshaped_marks=marks.reshape(10,2)
print("Reshaped marks:",reshaped_marks)
flattend_marks=marks.flatten()
print("Flattend marks:",flattend_marks)

Reshaped marks: [[65 75]
 [86 98]
 [75 77]
 [78 79]
 [89 57]
 [68 90]
 [90 95]
 [68 89]
 [80 85]
 [88 90]]
Flattend marks: [65 75 86 98 75 77 78 79 89 57 68 90 90 95 68 89 80 85 88 90]


4.Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.

In [ ]:
new_student_marks=np.array([60,85,94,78])
marks_added=np.vstack((marks,new_student_marks))
print("New student marks added:",marks_added)

New student marks added: [[65 75 86 98]
 [75 77 78 79]
 [89 57 68 90]
 [90 95 68 89]
 [80 85 88 90]
 [60 85 94 78]]


5.Data Modification:**Apply operations to update marks, remove data, or identify unique information.

In [ ]:
print(marks)
marks[0,1]=80
print(marks)

[[75 77 86 98]
 [75 57 78 79]
 [89 95 68 90]
 [90 95 68 89]
 [80 85 88 90]]
[[75 80 86 98]
 [75 57 78 79]
 [89 95 68 90]
 [90 95 68 89]
 [80 85 88 90]]


In [ ]:
print(marks)
marks_removed=np.delete(marks,3,0)
print(marks_removed)

[[75 80 86 98]
 [75 57 78 79]
 [89 95 68 90]
 [90 95 68 89]
 [80 85 88 90]]
[[75 80 86 98]
 [75 57 78 79]
 [89 95 68 90]
 [80 85 88 90]]


In [ ]:
np.unique(marks)

array([57, 68, 75, 78, 79, 80, 85, 86, 88, 89, 90, 95, 98])

6.Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.

In [ ]:
marks_float=marks.astype(dtype=float)
print(marks_float)

[[75. 80. 86. 98.]
 [75. 57. 78. 79.]
 [89. 95. 68. 90.]
 [90. 95. 68. 89.]
 [80. 85. 88. 90.]]


7.Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.

In [ ]:
marks_view=marks.view()
marks_view[0,0]=100
print("Viewed marks:",marks_view)
print("original:",marks)

Viewed marks: [[100  80  86  98]
 [ 75  57  78  79]
 [ 89  95  68  90]
 [ 90  95  68  89]
 [ 80  85  88  90]]
original: [[100  80  86  98]
 [ 75  57  78  79]
 [ 89  95  68  90]
 [ 90  95  68  89]
 [ 80  85  88  90]]


In [ ]:
marks_copy=marks.copy()
marks_copy[1,0]=50
print("Marks copied:",marks_copy)
print("Original:",marks)

Marks copied: [[100  80  86  98]
 [ 50  57  78  79]
 [ 89  95  68  90]
 [ 90  95  68  89]
 [ 80  85  88  90]]
Original: [[100  80  86  98]
 [ 75  57  78  79]
 [ 89  95  68  90]
 [ 90  95  68  89]
 [ 80  85  88  90]]
