NumPy Mathematical Calculator
Objective:

To build a Python-based calculator using the NumPy library that performs:

*Basic arithmetic operations

*Statistical analysis

*Array manipulation

This project helps students understand how NumPy is used in real-world numerical computing tasks.

Key Features:
1. Basic Arithmetic Operations
Addition, Subtraction, Multiplication, Division
Power operations between two arrays
2. Statistical Operations
Mean, Median, Standard Deviation, Variance
Minimum, Maximum, Sum, Product
Shape, Size, and Data Type
3. Array Manipulation
Reshaping arrays (when possible)
Sorting and Reverse Sorting
Unique value extraction
Accessing first and last elements
Filtering values greater than the mean

In [1]:
import numpy as np

def input_array():
    try:
        return np.array(list(map(int,input("Enter numbers separated by space: ").split())))
    except ValueError:
        print("Invalid input! Enter only numbers.")
        return input_array()

def basic_operations():
    try:
        a = input_array()
        b = input_array()
        print(a)
        print(b)
        print("Add:", a + b)
        print("Subtract:", a - b)
        print("Multiply:", a * b)
        print("Divide:", a/b)
        print("Power:",a**b)
    except Exception as e:
        print("Error:", e)

def statistical_operations():
    try:
        arr = input_array()
        print(arr)
        print("Mean:", np.mean(arr))
        print("Median:", np.median(arr))
        print("Std Dev:", np.std(arr))
        print("Variance:",np.var(arr))
        print("Min:", np.min(arr))
        print("Max:", np.max(arr))
        print("Sum:",np.sum(arr))
        print("Product:",np.prod(arr))
        print("Shape of the array:",np.shape(arr))
        print("Size of the array elements:",np.size(arr))
        print("Data type:",arr.dtype)
    except Exception as e:
        print("Error:", e)

def array_manipulation():
    try:
        arr = input_array()
        print(arr)
        print("Sorted:", np.sort(arr))
        rev=np.sort(arr)[::-1]
        print("Reverse:", rev)
        print("Unique:", np.unique(arr))
        print("First element:",arr[0])
        print("Last element:",arr[-1])
        print("Values greater than Mean:", arr[arr > np.mean(arr)])
    except Exception as e:
        print("Error:", e)
while True:
        print("1. Basic Arithmetic Operations")
        print("2. Statistical Operations")
        print("3. Array Manipulation")
        print("4. Exit")
        try:
            ch = int(input("Enter choice: "))
            if ch == 1:
                basic_operations()
            elif ch == 2:
                statistical_operations()
            elif ch == 3:
                array_manipulation()
            elif ch == 4:
                print("Thank you for choosing Numpy Calculator!")
                break
            else:
                print("Invalid choice.")
        except Exception as e:
            print("Error:", e)


1. Basic Arithmetic Operations
2. Statistical Operations
3. Array Manipulation
4. Exit
Enter choice: 1
Enter numbers separated by space: 1 2 3
Enter numbers separated by space: 4 5 6
[1 2 3]
[4 5 6]
Add: [5 7 9]
Subtract: [-3 -3 -3]
Multiply: [ 4 10 18]
Divide: [0.25 0.4  0.5 ]
Power: [  1  32 729]
1. Basic Arithmetic Operations
2. Statistical Operations
3. Array Manipulation
4. Exit
Enter choice: 2
Enter numbers separated by space: 20 56 43 67 87
[20 56 43 67 87]
Mean: 54.6
Median: 56.0
Std Dev: 22.526428922490133
Variance: 507.43999999999994
Min: 20
Max: 87
Sum: 273
Product: 280724640
Shape of the array: (5,)
Size of the array elements: 5
Data type: int64
1. Basic Arithmetic Operations
2. Statistical Operations
3. Array Manipulation
4. Exit
Enter choice: 3
Enter numbers separated by space: 40 56 78 67 56
[40 56 78 67 56]
Sorted: [40 56 56 67 78]
Reverse: [78 67 56 56 40]
Unique: [40 56 67 78]
First element: 40
Last element: 56
Values greater than Mean: [78 67]
1. Basic Arithmetic Ope